export enum SdvxClearType {
    NO_PLAY = 'NO PLAY',
    PLAYED = 'PLAYED',
    CLEAR = 'CLEAR',
    EXCESSIVE_CLEAR = 'EXCESSIVE CLEAR',
    MAXXIVE_CLEAR = 'MAXXIVE CLEAR',
    ULTIMATE_CHAIN = 'ULTIMATE CHAIN',
    PERFECT_ULTIMATE_CHAIN = 'PERFECT ULTIMATE CHAIN',
}
