export enum SdvxClearType {
    NO_PLAY = 'NO PLAY',
    PLAYED = 'PLAYED',
    COMPLETE = 'CLEAR',
    EXCESSIVE_COMPLETE = 'EXCESSIVE CLEAR',
    ULTIMATE_CHAIN = 'ULTIMATE CHAIN',
    PERFECT_ULTIMATE_CHAIN = 'PERFECT ULTIMATE CHAIN',
}
